# Generated by Django 5.2.1 on 2025-05-18 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("ZAMBA", "Zamba"),
                            ("KUBUCA", "Kubuca"),
                            ("AFRIIA", "Afri'IA"),
                            ("WHATSAPP", "WhatsApp API"),
                        ],
                        max_length=20,
                    ),
                ),
                ("short_description", models.TextField()),
                ("description", models.TextField()),
                (
                    "features",
                    models.TextField(help_text="Digite cada recurso em uma nova linha"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("LIVE", "Live"), ("DEVELOPMENT", "Development")],
                        default="DEVELOPMENT",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem principal do produto",
                        null=True,
                        upload_to="products/featured/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Imagem para a galeria do produto",
                        upload_to="products/gallery/",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Texto alternativo para acessibilidade",
                        max_length=200,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("content", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                        help_text="Avaliação de 1 a 5 estrelas",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Foto do autor do depoimento",
                        null=True,
                        upload_to="testimonials/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
